name: NestJS Continuous Integration
on:
  pull_request:
    branches:
      - master
    paths:
      - 'nestjs/**'

jobs:
  Linting-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0
      - name : Cache
        uses: actions/cache@v2
        with:
          path: "nestjs/node_modules"
          key: node-modules-${{ hashFiles('nestjs/package.json') }}
      - run: npm ci
        working-directory: ./nestjs
      - run: npm run lint
        working-directory: ./nestjs

  Unit-Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'nestjs'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        working-directory: nestjs
        run: npm ci

      - name: Run Unit Tests
        working-directory: nestjs
        run: npm run test



