name: nestjs-deployment
on:
  push:
    branches:
      - master
    paths:
      - nestjs

jobs:
  build-and-push-docker-image-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./nestjs/
          file: ./nestjs/Dockerfile.NestJS
          push: true
          tags: magnussaunders/demo-api:nestjs
