name: nestjs-integration
on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Initialize Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0
          cache: npm
          cache-dependency-path: ./nestjs/package-lock.json

      - name: Install Dependencies
        working-directory: nestjs
        run: npm install


      - name: Run linting test
        working-directory: nestjs
        run: npm run lint

#  unit-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v2
#
#      - name: Initialize Node
#        uses: actions/setup-node@v2
#        with:
#          node-version: 16.16.0
#          cache: npm
#          cache-dependency-path: ./nestjs/package-lock.json
#
#      - name: Install Dependencies
#        working-directory: nestjs
#        run: npm install
#
#      - name: Run unit tests
#        working-directory: nestjs
#        run: npm run test