name: NestJS Continuous Integration
on:
  pull_request:
    branches:
      - master
    paths:
      - 'api/**'

jobs:
  lint-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Initialize Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0
          cache: npm
          cache-dependency-path: ./api/package-lock.json

      - name: Install Dependencies
        working-directory: api
        run: npm install


      - name: Run linting test
        working-directory: api
        run: npm run lint

#   unit-tests:
#      runs-on: ubuntu-latest
#      steps:
#        - name: Checkout repo
#          uses: actions/checkout@v2

#        - name: Initialize Node
#          uses: actions/setup-node@v2
#          with:
#            node-version: 16.16.0
#            cache: npm
#            cache-dependency-path: ./api/package-lock.json

#        - name: Install Dependencies
#          working-directory: api
#          run: npm install

#        - name: Run unit tests
#          working-directory: api
#          run: npm run test
