name: NestJS Continuous Integration
on:
  push:
    branches:
      - master
    paths:
      - 'nestjs/**'

jobs:
  Linting Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{secrets.NODE_VERSION}}

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint Tests
        run: npm run lint

  Unit Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{secrets.NODE_VERSION}}

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test



